#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit the data as a browser JS bundle (global assignments) so the site is
fully static and works even when opened via file://."""
import json, os

D = os.path.join(os.path.dirname(__file__), "..", "data")
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "data.js")

hexagrams = json.load(open(os.path.join(D, "hexagrams.json"), encoding="utf-8"))
trigrams  = json.load(open(os.path.join(D, "trigrams.json"), encoding="utf-8"))
lookup    = json.load(open(os.path.join(D, "lookup.json"), encoding="utf-8"))
kangxi    = json.load(open(os.path.join(D, "kangxi_strokes.json"), encoding="utf-8"))

def dump(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by scripts/emit_js_bundle.py — do not edit by hand. */\n")
    f.write("window.YJ_HEXAGRAMS=" + dump(hexagrams) + ";\n")
    f.write("window.YJ_TRIGRAMS=" + dump(trigrams) + ";\n")
    f.write("window.YJ_LOOKUP=" + dump(lookup) + ";\n")
    f.write("window.YJ_KANGXI=" + dump(kangxi) + ";\n")

print("OK wrote", OUT, "%.0f KB" % (os.path.getsize(OUT) / 1024))
